# Generated by Django 2.0.3 on 2018-03-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('password', models.CharField(max_length=80, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
